name: No Fixups
description: |
  GitHub Action to use in pull requests to check if there are accidental
  commits that should have been autosquashed first.
author: Matijs Brinkhuis
inputs:
  skip-checkout:
    description: |
      Skip the actions/checkout because you are using your own checkout.
      Set `fetch-depth` and `ref` yourself. See below for values.
    default: 'false'

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - name: Check if this is a pull request
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo "::error::This action can only be run on pull_request events"
        exit 1
    - name: Checkout
      if: ${{ inputs.skip-checkout == 'false' }}
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Check if there are 'amend!', 'fixup!', and 'squash!' commits
      run: ${{ github.action_path }}/action.sh

branding:
  icon: git-commit
  color: red
