name: No Fixups
description: |
  GitHub Action to use in pull requests to check if there are accidental
  commits that should have been autosquashed first.
author: Matijs Brinkhuis
inputs:
  skip-checkout:
    description: |
      Skip the actions/checkout because you are using your own checkout.
      Set `fetch-depth` and `ref` yourself. See below for values.
    default: 'false'

runs:
  using: composite
  steps:
    - name: Check if this is a pull request
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo '### Error' >> ${GITHUB_STEP_SUMMARY}
        echo '' >> ${GITHUB_STEP_SUMMARY}
        echo 'This action can only be run on pull requests.' >> ${GITHUB_STEP_SUMMARY}
        exit 1
      shell: bash

    - name: Checkout
      if: ${{ inputs.skip-checkout == 'false' }}
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set GitHub Action path
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: echo "${ACTION_PATH}" >> ${GITHUB_PATH}
      shell: bash

    - name: Check if there are 'amend!', 'fixup!', and 'squash!' commits
      run: action.sh
      shell: bash

branding:
  icon: git-commit
  color: red
